spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

kakao:
  api:
    key: ${KAKAO_API_KEY}

chat:
  websocket:
    allowed-origins: ${WS_ALLOWED_ORIGINS}