-- V10: 분할 결제 (포트원 빌링키). ERD 의 payment_method / card / easy_pay / mobile / payment_group / payment / payment_log

CREATE TABLE payment_method (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    user_id bigint not null,
    billing_key varchar(255) not null unique,
    type varchar(255) not null check ((type in ('CARD','EASY_PAY','MOBILE'))),
    primary key (id)
);

CREATE INDEX idx_payment_method_user_id ON payment_method (user_id);

CREATE TABLE card (
    payment_method_id bigint not null,
    name varchar(255),
    number varchar(255),
    brand varchar(255),
    primary key (payment_method_id)
);

CREATE TABLE easy_pay (
    payment_method_id bigint not null,
    provider varchar(255),
    primary key (payment_method_id)
);

CREATE TABLE mobile (
    payment_method_id bigint not null,
    phone_number varchar(255),
    primary key (payment_method_id)
);

CREATE TABLE payment_group (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    match_id bigint not null unique,
    partner_id bigint not null,
    fare integer not null,
    passenger_count integer not null,
    remaining_balance integer not null,
    platform_charge integer not null,
    status varchar(255) not null check ((status in ('IN_PROGRESS','PARTIALLY_FAILED','COMPLETED'))),
    primary key (id)
);

CREATE TABLE payment (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    payment_group_id bigint not null,
    pg_payment_id varchar(255),
    user_id bigint not null,
    payment_method_id bigint,
    amount integer not null,
    status varchar(255) not null check ((status in ('READY','PAID','FAILED','CANCELED','COVERED'))),
    type varchar(255) not null check ((type in ('SHARE','COVER'))),
    currency varchar(255) not null check ((currency in ('KRW'))),
    order_name varchar(255) not null,
    fail_code varchar(255),
    cancel_at timestamp(6) with time zone,
    cancel_reason varchar(255),
    primary key (id)
);

CREATE INDEX idx_payment_user_id ON payment (user_id);
CREATE UNIQUE INDEX idx_payment_pg_payment_id ON payment (pg_payment_id);

CREATE TABLE payment_log (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    payment_id bigint not null,
    amount integer not null,
    status varchar(255) not null check ((status in ('READY','PAID','FAILED','CANCELED','COVERED'))),
    type varchar(255) not null check ((type in ('SHARE','COVER'))),
    fail_code varchar(255),
    primary key (id)
);

CREATE INDEX idx_payment_log_payment_id ON payment_log (payment_id);

ALTER TABLE IF EXISTS card ADD CONSTRAINT fk_card_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method;
ALTER TABLE IF EXISTS easy_pay ADD CONSTRAINT fk_easy_pay_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method;
ALTER TABLE IF EXISTS mobile ADD CONSTRAINT fk_mobile_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method;
ALTER TABLE IF EXISTS payment ADD CONSTRAINT fk_payment_payment_group FOREIGN KEY (payment_group_id) REFERENCES payment_group;
ALTER TABLE IF EXISTS payment_log ADD CONSTRAINT fk_payment_log_payment FOREIGN KEY (payment_id) REFERENCES payment;
