-- V1: 베이스라인 스키마 = 2026-09-09 배포(마지막 정상 배포) 시점의 prod 스키마
-- 이미 테이블이 있는 prod 는 baseline-on-migrate 로 이 버전을 '적용됨'으로 기록하고 V2 부터 실행한다.
-- 새 환경(로컬 docker, CI)은 이 파일부터 실행된다. 적용된 마이그레이션은 절대 수정하지 말고 새 V{n} 을 추가한다.

CREATE TABLE chat_message (
    chat_room_id bigint not null,
    created_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    user_id bigint not null,
    content varchar(1000),
    status varchar(255) not null check ((status in ('ACTIVE','DELETED'))),
    type varchar(255) not null check ((type in ('TEXT','LOCATION'))),
    primary key (id)
);

CREATE TABLE chat_room (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    party_id bigint not null unique,
    departure varchar(255) not null,
    destination varchar(255) not null,
    status varchar(255) not null check ((status in ('ACTIVE','CLOSED','ARCHIVED'))),
    primary key (id)
);

CREATE TABLE chat_room_user (
    notification_muted boolean not null,
    chat_room_id bigint not null,
    joined_at timestamp(6) with time zone not null,
    last_read_message_id bigint,
    left_at timestamp(6) with time zone,
    user_id bigint not null,
    primary key (chat_room_id, user_id)
);

CREATE TABLE driver_report (
    reporter_latitude float(53),
    reporter_longitude float(53),
    created_at timestamp(6) with time zone not null,
    driver_id bigint,
    id bigint generated by default as identity,
    party_id bigint,
    reporter_id bigint not null,
    updated_at timestamp(6) with time zone,
    status varchar(255) not null check ((status in ('REPORTED','CALL_CONFIRMED','CALL_NOT_MADE'))),
    primary key (id)
);

CREATE TABLE driver_setting (
    call_enabled boolean not null,
    created_at timestamp(6) with time zone not null,
    driver_id bigint not null,
    updated_at timestamp(6) with time zone,
    primary key (driver_id)
);

CREATE TABLE favorite_place (
    latitude float(53),
    longitude float(53),
    place_sequence integer,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    user_id bigint not null,
    place_name varchar(255) not null,
    road_name varchar(255),
    primary key (user_id, place_name)
);

CREATE TABLE local_user (
    created_at timestamp(6) with time zone not null,
    id bigint not null,
    updated_at timestamp(6) with time zone,
    login_id varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
);

CREATE TABLE match_room (
    capacity integer not null,
    departure_lat float(53) not null,
    departure_lng float(53) not null,
    departure_radius integer not null,
    destination_lat float(53) not null,
    destination_lng float(53) not null,
    destination_radius integer not null,
    estimated_fare integer not null,
    estimated_time integer not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    match_started_at timestamp(6) with time zone,
    taxi_driver_id bigint,
    updated_at timestamp(6) with time zone,
    departure varchar(255) not null,
    destination varchar(255) not null,
    route TEXT not null,
    status varchar(255) check ((status in ('ACTIVE','COMPLETED','MATCHING','DRIVER_ASSIGNED','IN_RIDE','FINISHED','CANCELED'))),
    primary key (id)
);

CREATE TABLE refresh_token (
    cancelled_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    user_id bigint not null,
    jti uuid not null,
    primary key (jti)
);

CREATE TABLE taxi (
    seats integer not null,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    taxi_driver_id bigint not null unique,
    updated_at timestamp(6) with time zone,
    plate_number varchar(255) not null,
    type varchar(255) not null,
    primary key (id)
);

CREATE TABLE taxi_driver (
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    user_id bigint not null unique,
    verified_at timestamp(6) with time zone,
    bank_name varchar(255) not null,
    bank_number varchar(255) not null,
    fcm_token varchar(255),
    qualification_number varchar(255) not null,
    status varchar(255) not null check ((status in ('PENDING','VERIFIED'))),
    primary key (id)
);

CREATE TABLE user_match_room (
    joined_at timestamp(6) with time zone not null,
    match_id bigint not null,
    user_id bigint not null,
    primary key (match_id, user_id)
);

CREATE TABLE user_profile (
    birth_date timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    id bigint not null,
    updated_at timestamp(6) with time zone,
    email varchar(255) not null,
    gender varchar(255) not null check ((gender in ('MALE','FEMALE'))),
    name varchar(255) not null,
    pass_ci varchar(255),
    phone_number varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE users (
    badge_id bigint,
    created_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    public_id uuid not null unique,
    fcm_token varchar(255),
    image_url varchar(255),
    login_type varchar(255) not null check ((login_type in ('LOCAL','SOCIAL'))),
    nickname varchar(255) unique,
    primary key (id)
);

CREATE INDEX idx_chat_message_room_id on chat_message (chat_room_id, id);

ALTER TABLE IF EXISTS driver_setting add constraint FK9rdht619wb5wtbw4bq9d7pbh4 foreign key (driver_id) references taxi_driver;

ALTER TABLE IF EXISTS taxi add constraint FKlemp95pjedgbx9vjrk5ik1xnx foreign key (taxi_driver_id) references taxi_driver;

ALTER TABLE IF EXISTS user_match_room add constraint FKiobtg1htl1svyhauq3rhyiej6 foreign key (match_id) references match_room;
