CREATE TABLE chat_report (
    id bigint generated by default as identity,
    user_id bigint not null,
    reported_user_id bigint not null,
    chat_message_id bigint not null,
    reason varchar(255) not null check ((reason in ('ABUSE','SPAM','FRAUD','SEXUAL','ETC'))),
    description varchar(500),
    created_at timestamp(6) with time zone not null,
    primary key (id)
);

CREATE UNIQUE INDEX uk_chat_report_user_message ON chat_report (user_id, chat_message_id);