CREATE TABLE search_history (
    search_history_id bigint generated by default as identity,
    user_id bigint not null,
    search_query varchar(100) not null,
    created_at timestamp(6) not null,
    primary key (search_history_id)
);

ALTER TABLE search_history ADD CONSTRAINT fk_search_history_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- 같은 유저의 같은 검색어는 한 줄만 유지한다 (다시 검색하면 기존 행을 지우고 새로 넣는다)
CREATE UNIQUE INDEX uk_search_history_user_query ON search_history (user_id, search_query);

-- 내 검색기록 최신순 조회
CREATE INDEX idx_search_history_user_created_at ON search_history (user_id, created_at DESC);
