-- 메시지 저장과 색인 요청을 원자적으로 기록한다. ES 장애 시에도 요청을 보존한다.
CREATE TABLE chat_search_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    deleted BOOLEAN NOT NULL,
    sent_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    queued_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    next_attempt_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_chat_search_outbox_due ON chat_search_outbox (next_attempt_at, id);
